Ext.onReady(function(){
	Ext.get("b1").on("click",function(){
		b1.show()
	})
	Ext.get("b2").on("click",function(){
		b2.show()
	})
	Ext.get("b3").on("click",function(){
		b3.show()
	})
	Ext.get("b4").on("click",function(){
		b4.show()
	})	
});