/**
 * ClassName 部门实体数据集
 */
Ext.define("AM.store.DeptStore",{
	extend:'Ext.data.Store',
	model:'AM.model.DeptModel',
	proxy:{
		api:{
			update:'/extjs/extjs!updateDeptList.action',//更新
			remove:'/extjs/extjs!updateDeptList.action'//删除
		},
		type:'ajax',
		url:'/extjs/extjs!readDeptForGrid.action',//查询
		reader:{
			type:'json',
			root:'topics'
		},
		writer:{
			type:'json'
		}
	},
	autoLoad:true
});