/**
 * ClassName 部门实体数据集
 */
Ext.define("AM.store.DeptStore",{
	extend:'Ext.data.Store',
	model:'AM.model.DeptModel',
	proxy:{
		type:'ajax',
		url:'/extjs/extjs!readDeptForGrid.action',
		reader:{
			type:'json',
			root:'topics'//指定从什么开始读
		},
		writer:{
			type:'json'
		}
	},
	autoLoad:true
});